/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ej_proyecto;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class frm_Login extends javax.swing.JFrame {

    /**
     * Creates new form frm_Login
     */
    public frm_Login() {
        initComponents();
    }
    
    public boolean RevisarUsuario(String usuario){
    //funcion para reivisar si el usuario existe dentro de la BD
    
    PreparedStatement ps;
    ResultSet rs;
    boolean checkUser = false;
    String query = "Select *from `usuarios` where `usuario` =?";
    try {
    
    ps= MyConnection.getConnection().prepareStatement(query);
    ps.setString(1,usuario);
    
    rs=ps.executeQuery();
    
    if(rs.next()){
    
    checkUser = true;
    }
    
    
    }
    
    catch (SQLException ex){
    
    JOptionPane.showMessageDialog(null, "error" + ex);
    }
    
    return checkUser;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ibl_usuario = new javax.swing.JLabel();
        ibl_clave = new javax.swing.JLabel();
        Nombre_usuario = new javax.swing.JTextField();
        Nombre_usuario1 = new javax.swing.JTextField();
        Logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        B_inicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 141, 109));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ibl_usuario.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        ibl_usuario.setText("Usuario:");

        ibl_clave.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        ibl_clave.setText("Clave:");

        Nombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_usuarioActionPerformed(evt);
            }
        });

        Nombre_usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_usuario1ActionPerformed(evt);
            }
        });

        Logo.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Owner\\Documents\\Miniproyecto 5to\\Pagina web\\imagenes\\consola.png")); // NOI18N
        Logo.setText("J&M Iluminers");

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel2.setText("Inicio Sesion:");

        B_inicio.setText("Inicio");
        B_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_inicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ibl_clave)
                                .addGap(18, 18, 18)
                                .addComponent(Nombre_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ibl_usuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel2))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(B_inicio)
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ibl_usuario))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibl_clave)
                    .addComponent(Nombre_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(B_inicio)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 480, 330));

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Owner\\Downloads\\kiyotaka ayano.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 1060, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_usuarioActionPerformed

    private void Nombre_usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_usuario1ActionPerformed

    private void B_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_inicioActionPerformed
        // TODO add your handling code here:
        
      
          PreparedStatement ps;
          ResultSet rs;
        String Usuario, Clave;
        Usuario = Nombre_usuario.getText();
        Clave = String.valueOf(Nombre_usuario1.getText());
        String query = "SELECT * FROM `usuarios` WHERE `Usuario` =? AND `Clave` =?";
        
        try{
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, Usuario);
            ps.setString(2, Clave);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
            Formi mf = new Formi();
            mf.setVisible(true);
            mf.pack();
            this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Usuario o Clave incorrectos", "Fallo en Acesso",2);
            }
            }   catch (SQLException ex){
            Logger.getLogger(frm_Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error" + ex);
            
        }
        
        
        
        
        
        
//        if("Admin".equals(Usuario) && "Admin".equals(Clave)){
//        
//            JOptionPane.showMessageDialog(null, "Bienvenido " + Usuario, "Inicio sesion", HEIGHT);
//        
//            Formi mf = new Formi();
//            mf.setVisible(true);
//            mf.pack();
//            this.dispose();
//        }
//        
//        else{
//        
//        JOptionPane.showMessageDialog(null, "Que gay no sabe iniciar sesion", null, HEIGHT);
//        
//        }
    }//GEN-LAST:event_B_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_inicio;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField Nombre_usuario;
    private javax.swing.JTextField Nombre_usuario1;
    private javax.swing.JLabel ibl_clave;
    private javax.swing.JLabel ibl_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
